version: "3"

services:
  app-ddd:
    build:
      context: .
    container_name: app-ddd
    networks:
      - node-ddd
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    tty: true

networks:
  node-ddd:
    driver: bridge
